#!/usr/bin/env bash

# A sample pre-connect check
#
# Warms DNS before connecting to hosts in parallel
#
# These environment variables are available:
# KAMAL_RECORDED_AT
# KAMAL_PERFORMER
# KAMAL_VERSION
# KAMAL_HOSTS
# KAMAL_ROLE (if set)
# KAMAL_DESTINATION (if set)
# KAMAL_RUNTIME

IFS=','; for host in $KAMAL_HOSTS; do
  ssh root@$host exit 2>&1 | while IFS= read -r line; do
    url=$(echo "$line" | grep -o 'https://login\.tailscale\.com/a/[a-zA-Z0-9_-]*')
    if [ -n "$url" ]; then
      $BROWSER "$url"
      break
    fi
  done
done
