# Name of your site. Used to uniquely configure containers.
service: maintenance
image: joedupuis/maintenance

servers:
  - maintenance

proxy:
  host: null

registry:
  username: joedupuis
  password:
    - KAMAL_REGISTRY_PASSWORD

proxy:
  healthcheck:
    path: /up

builder:
  arch: amd64
