# Name of your site. Used to uniquely configure containers.
service: maintenance

# Name of the container image.
image: joedupuis/maintenance

# Deploy to these servers.
servers:
  - maintenance
  - beankeeper

proxy:
  host: maintenance


# Use GIT_URL from env to auto-update site via git pulls.
# Remember to run `kamal env push` after making changes!
env:
  secret:
    - GIT_URL

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: joedupuis

  # Always use an access token rather than real password when possible.
  password:
    - SKIFF_REGISTRY_PASSWORD

proxy:
  healthcheck:
    path: /up

builder:
  arch: amd64

accessories:
  cloudflared:
    host: maintenance
    image: cloudflare/cloudflared:latest
    cmd: tunnel --no-autoupdate run
    env:
      secret:
        - TUNNEL_TOKEN
